2018-11-11 00:15:15,090 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 00:15:16,642 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 00:15:36,962 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 00:17:15,675 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 00:17:17,292 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 00:17:29,940 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:25:13,114 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 00:25:14,541 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 00:25:21,927 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:25:24,252 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:25:28,240 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:25:34,341 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 00:25:39,245 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:27:48,069 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 00:27:49,784 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 00:27:54,448 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:27:58,124 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 00:28:01,047 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:101]
2018-11-11 12:41:41,169 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:41:42,844 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 12:45:10,244 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:45:12,080 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 12:45:29,742 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:45:40,556 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 12:45:43,665 ERROR: An exception happenning: search() missing 1 required positional argument: 'indistince_name' [in D:\python\xeekwebsite_flask\xeekwebsite_server\util.py:11]
2018-11-11 12:45:43,665 ERROR: Exception on /home/search/ [GET] [in C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-11-11 12:50:11,220 INFO: 初始化日志配置成功... [in d:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:50:14,777 ERROR: An exception happenning: search() missing 1 required positional argument: 'indistince_name' [in d:\python\xeekwebsite_flask\xeekwebsite_server\util.py:11]
2018-11-11 12:50:14,784 ERROR: Exception on /home/search/ [GET] [in C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-11-11 12:51:18,166 ERROR: An exception happenning: search() missing 1 required positional argument: 'indistince_name' [in d:\python\xeekwebsite_flask\xeekwebsite_server\util.py:11]
2018-11-11 12:51:18,185 ERROR: Exception on /home/search/ [GET] [in C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-11-11 12:52:14,599 INFO: 初始化日志配置成功... [in d:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:53:53,956 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:53:56,912 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 12:54:03,315 ERROR: An exception happenning: search() missing 1 required positional argument: 'indistince_name' [in D:\python\xeekwebsite_flask\xeekwebsite_server\util.py:11]
2018-11-11 12:54:03,317 ERROR: Exception on /home/search [GET] [in C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-11-11 12:55:51,996 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:55:54,808 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 12:56:00,484 ERROR: Exception on /home/search [GET] [in C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: search() missing 1 required positional argument: 'indistince_name'
2018-11-11 12:56:34,611 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 12:56:37,008 ERROR: An exception happenning: search() missing 1 required positional argument: 'indistince_name' [in D:\python\xeekwebsite_flask\xeekwebsite_server\util.py:11]
2018-11-11 12:56:37,010 ERROR: Exception on /home/search [GET] [in C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xeekseven\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-11-11 14:16:49,917 INFO: 初始化日志配置成功... [in d:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:18:44,112 INFO: 初始化日志配置成功... [in d:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:20:43,676 INFO: / 搜索到数据 [in d:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:103]
2018-11-11 14:22:44,408 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:22:46,496 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:22:49,753 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:102]
2018-11-11 14:22:55,291 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:102]
2018-11-11 14:25:04,064 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:25:16,485 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:25:18,214 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:25:30,111 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:25:32,140 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:26:23,600 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:26:32,944 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:102]
2018-11-11 14:26:43,991 INFO: / 搜索到数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:102]
2018-11-11 14:26:48,282 INFO: 查询markdown:SELECT * FROM article_markdown WHERE markdown_id = ?,id:1b541bc0-e0cb-11e8-b3b0-5413793bd976 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\article.py:43]
2018-11-11 14:27:06,145 ERROR: /auth/register 发生了错误:Incorrect password.(密码不正确)... [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\auth.py:72]
2018-11-11 14:27:20,126 INFO: /auth/register 用户登录:xeekseven [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\auth.py:70]
2018-11-11 14:27:20,134 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:27:42,313 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:27:44,119 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:28:59,538 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:29:01,361 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:29:44,957 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:48:35,215 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:48:36,928 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:48:39,772 INFO: 删除的article ID:%s [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\article.py:125]
2018-11-11 14:48:44,427 INFO: 查不到要删除的Markdown或者article ID:%s [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\article.py:115]
2018-11-11 14:48:48,046 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
2018-11-11 14:49:10,787 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 14:50:07,195 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 15:28:41,147 INFO: 初始化日志配置成功... [in D:\python\xeekwebsite_flask\xeekwebsite_server\LogFactory.py:40]
2018-11-11 15:28:43,039 INFO: / 获取到所有数据 [in D:\python\xeekwebsite_flask\xeekwebsite_server\view\home.py:22]
